module.exports = {
  "textbookSidebar": [
    {
      "type": "doc",
      "id": "intro",
      "label": "Introduction"
    },
    {
      "type": "category",
      "label": "Module 1 - ROS 2 Foundations",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "module-1"
        }
      ]
    },
    {
      "type": "category",
      "label": "Module 2 - Digital Twins (Gazebo & Unity)",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "module-2"
        }
      ]
    },
    {
      "type": "category",
      "label": "Module 3 - Isaac Sim & Navigation",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "module-3"
        }
      ]
    },
    {
      "type": "category",
      "label": "Module 4 - Vision-Language-Action (VLA) Systems",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "module-4"
        }
      ]
    }
  ]
};
